-- Generated by nwg-displays on 2026-07-05 at 18:40:10. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@165.0",
    position = "3080x2553",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@143.97",
    position = "5640x1433",
    scale = 1.0,
    bitdepth = 10,
    transform = 1
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@144.0",
    position = "1640x2240",
    scale = 1.0,
    bitdepth = 10,
    transform = 3
})
